import Foundation
import Combine

struct TodayMetrics {
    let sleepHours: Double?
    let sleepAvg: Double?
    let restingHR: Int?
    let restingHRAvg: Double?
    let steps: Int?
    let stepsAvg: Double?
    let hrv: Double?
    let hrvAvg: Double?

    static let empty = TodayMetrics(
        sleepHours: nil, sleepAvg: nil,
        restingHR: nil, restingHRAvg: nil,
        steps: nil, stepsAvg: nil,
        hrv: nil, hrvAvg: nil
    )
}

/// Loads raw health data for the Home tab: metrics + trend charts.
/// Alerts are generated by AI (see InsightGenerator), not here.
@MainActor
final class HomeDataLoader: ObservableObject {

    @Published var metrics: TodayMetrics = .empty
    @Published var sleepTrend: [ChartPoint] = []
    @Published var hrvTrend: [ChartPoint] = []
    @Published var isLoading = false
    @Published var loadError: String?
    @Published var daysWithData = 0
    @Published var window: TimeWindow = .days7

    func load(healthStore: HealthStore, window: TimeWindow) async {
        self.window = window
        isLoading = true
        loadError = nil
        defer { isLoading = false }

        do {
            let snapshots = try await healthStore.snapshots(lastDays: window.dayCount)
            daysWithData = snapshots.count
            guard let last = snapshots.last else {
                metrics = .empty
                sleepTrend = []
                hrvTrend = []
                return
            }

            let sleepArr = snapshots.compactMap { $0.snapshot.sleep.asleepMinutes }.map { Double($0) / 60 }
            let restingArr = snapshots.compactMap { $0.snapshot.heart.restingBpm }.map(Double.init)
            let hrvArr = snapshots.compactMap { $0.snapshot.heart.hrvSdnnMs }
            let stepsArr = snapshots.compactMap { $0.snapshot.activity.steps }.map(Double.init)

            metrics = TodayMetrics(
                sleepHours: last.snapshot.sleep.asleepMinutes.map { Double($0) / 60 },
                sleepAvg: sleepArr.avg,
                restingHR: last.snapshot.heart.restingBpm,
                restingHRAvg: restingArr.avg,
                steps: last.snapshot.activity.steps,
                stepsAvg: stepsArr.avg,
                hrv: last.snapshot.heart.hrvSdnnMs,
                hrvAvg: hrvArr.avg
            )

            sleepTrend = snapshots.compactMap { item in
                guard let m = item.snapshot.sleep.asleepMinutes else { return nil }
                return ChartPoint(date: item.date, value: Double(m) / 60)
            }
            hrvTrend = snapshots.compactMap { item in
                guard let m = item.snapshot.heart.hrvSdnnMs else { return nil }
                return ChartPoint(date: item.date, value: m)
            }
        } catch {
            loadError = error.localizedDescription
        }
    }
}

private extension Array where Element == Double {
    var avg: Double? { isEmpty ? nil : reduce(0, +) / Double(count) }
}
